services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - ${PORT}:8080
    environment:
      PORT: ${PORT}
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local
