services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USER}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - ${PORT}:8080
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local
